In [1]:
from mlopskit import make

model_db = make("cache/feature_store-v1", db_name="dqn.db")

2023-05-29 22:47:48 [info     ] APIs of mlopskit               model_name=feature_store model_version=1 ops_type=cache
2023-05-29 22:47:49 [info     ] The list of all versions for the current model is [1, 2].
2023-05-29 22:47:49 [warning  ] The version 1 is out of date. You should consider upgrading to version `v2`.
2023-05-29 22:47:49 [info     ] Usage of mlopskit-cache        Params={'db_type': 'rlite/redis/sfdb/diskcache, default:rlite', 'return_type': 'dblink/dbobj, default: dbobj', 'db_name': 'default: rlite_model.cache'}


In [2]:
from minirl.brain.dqn import DQNAgent
import numpy as np

test=DQNAgent(2,3,64,0.01,model_db=model_db)

In [18]:
dd=test.model.predict(np.array([[1,0,0,0]]))
dd[0][0]=1.1
dd

array([[ 1.1       , -0.01584985,  0.06314397]])

In [24]:
state = [1 if i==0 else 0 for i in range(40)]
#state


In [10]:
import numpy as np
reward = 1

g=reward + 0.98 * np.max(dd)

In [32]:
%%time
state = [10.99,91.9]
next_state = np.array([[1.99,9100.2]])
state=next_state
for i in range(10):
    c = test.act([state],"test9")
    print(c,type(c))

0 <class 'numpy.int64'>
0 <class 'numpy.int64'>
0 <class 'numpy.int64'>
0 <class 'numpy.int64'>
0 <class 'numpy.int64'>
0 <class 'numpy.int64'>
0 <class 'numpy.int64'>
0 <class 'numpy.int64'>
0 <class 'numpy.int64'>
0 <class 'numpy.int64'>
CPU times: user 1.59 ms, sys: 3.96 ms, total: 5.55 ms
Wall time: 5.61 ms


In [ ]:
%%time
state = [1 if i==0 else 0 for i in range(40)]

for i in range(10):
    c = test.act([[1,0,0,0]],"test3")
    print(c,type(c))

In [21]:
import numpy as np

state=  np.array([[1 if i==0 else 0 for i in range(40)]])  #np.array([[1,0,0,0]])
next_state= np.array([[1 if i==1 else 0 for i in range(40)]])  #np.array([[0,1,0,0]])
state = np.array([[0.99,0.9]])
next_state = np.array([[1.99,0.2]])
for i in range(2):
    test.learn(state,0,next_state,1.99,"test9")

In [23]:
test.model.load_weights("test9")

(array([[ 0.62319756,  0.18295442, -0.68855334, -0.45282642, -0.0569859 ,
          0.70645673, -0.3863557 ,  0.46239844, -0.11245185, -0.19596921,
         -0.66098099,  0.14212486, -0.45808603,  0.5702784 ,  0.19324617,
          0.22099766,  0.54881063, -0.30083418,  0.55405734,  0.33434349,
          0.30428692, -0.3020188 ,  0.35563852, -0.35250736, -0.16404296,
          0.12335234, -0.34544358, -0.48158699,  0.63770516, -0.16992084,
         -0.55261945, -0.6060563 , -0.09063241, -0.13669083,  0.61076222,
          0.08107561,  0.33554733, -0.46574566, -0.47300081,  0.49678826,
         -0.47348677,  0.89727173,  0.99548062,  0.8836967 , -0.39970594,
          0.54294814,  0.68975682,  0.26639076, -0.24931375,  0.06148358,
          0.41909291,  0.32199581,  0.86838852,  0.44986634, -0.48881626,
          0.29229849, -0.45328189,  0.50654563,  0.7253842 ,  0.73173889,
         -0.16744357, -0.37225832, -0.49391013,  0.4451382 ],
        [-0.06713611, -0.51306005,  0.20250549, -0

In [14]:
import numpy as np

np.random.normal(
            scale=0.1, size=(3, 7)
        )

array([[ 0.08477906, -0.01357327,  0.24057955, -0.15129921, -0.00483628,
        -0.07707545, -0.05678914],
       [-0.01745422, -0.14687918,  0.02317782, -0.06951836, -0.01262851,
        -0.17151188,  0.08863943],
       [-0.06284439,  0.07291588,  0.09590553, -0.0109476 , -0.14697387,
        -0.04037211,  0.28882319]])

In [30]:
test.model.load_weights("test4")

(array([[-0.01969739, -0.11471969,  0.05501801, ...,  0.16768471,
          0.01483978,  0.17210375],
        [-0.07103074, -0.04512562,  0.01010342, ...,  0.05208623,
          0.14734517,  0.06268044],
        [-0.07800155, -0.09138871,  0.01161425, ..., -0.03734528,
          0.04094503,  0.02924816],
        ...,
        [ 0.16336601,  0.08046579, -0.0925792 , ..., -0.02805661,
          0.02562365,  0.20028932],
        [ 0.18525556, -0.01820518,  0.19038752, ..., -0.01365032,
          0.01629806, -0.01243669],
        [ 0.01527601,  0.19987031, -0.17723112, ...,  0.02645274,
         -0.01279341,  0.05682846]]),
 array([ 0.        ,  0.        ,  0.00508469, -0.00052474,  0.        ,
         0.01339939, -0.00443335,  0.        ,  0.00382087,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.01364747,
        -0.00303874, -0.00094674,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.01484657, -0.01591766,  0.        ,
        

In [20]:
test.model.load_weights("test3")

(array([[-1.75117718e-03,  5.13678545e-04, -3.33886184e-02,
         -1.33714218e-01,  6.19261818e-02, -5.37717804e-02,
          1.38536304e-01, -5.67764507e-02, -2.56168014e-02,
         -4.39359894e-02,  9.07571080e-02,  1.82529822e-02,
         -4.76111401e-02,  2.51340027e-01,  6.54235308e-02,
         -3.58947672e-02, -7.59986244e-02,  1.37644510e-01,
         -1.51180875e-02, -1.12269754e-01, -3.00111015e-01,
          3.84792665e-02, -1.51291962e-01,  7.91412450e-02,
          4.76205366e-02,  8.47885118e-02,  1.02876282e-01,
          1.26352567e-02,  1.04163457e-01, -1.50305965e-01,
         -7.42076956e-02, -1.13332782e-01, -2.77776557e-03,
          4.81316323e-02, -2.13049359e-01, -7.47722439e-02,
          1.65606777e-01,  9.74915938e-02,  2.65304855e-01,
         -1.10638797e-02, -1.49570207e-01,  3.59865730e-02,
          1.27839967e-01, -2.04206157e-02, -1.21953391e-01,
         -9.21498913e-02, -1.23432302e-01,  9.54264588e-04,
          5.70365881e-02,  5.94946596e-0