In [3]:
from minirl.brain.es import Model


test_model = Model(4,64,3)




In [4]:
test_model.predict([1,0,0,0])

(array([[-14.4829959 ,  16.74821895,  30.55435607]]), array([[-4.07639034]]))

In [10]:
test_model.predict([0,1,0,0])

(array([[-20.35808437,  -7.67268228,  15.71366702]]), array([[10.16417959]]))

In [11]:
test_model.predict([0,0,1,0])

(array([[ 1.74806478, 15.12215296, 14.32668046]]), array([[-12.93622419]]))

In [18]:
x = []
learning_rate=0.01
population_size =1
sigma = 0.1
import numpy as np
weights = test_model.get_weights()
for w in weights:
    x.append(np.random.randn(*w.shape))

population = []

population.append(x)
rewards = np.array([1,0,0])
for index, w in enumerate(weights):
    A = np.array([p[index] for p in population])
    weights[index] = (
                    w
                    + learning_rate
                    / (population_size * sigma)
                    * np.dot(A.T, rewards).T
                )

A

ValueError: shapes (64,4,1) and (3,) not aligned: 1 (dim 2) != 3 (dim 0)