In [2]:
from minirl.brain.pucb import PUCB

from mlopskit import make
model_db = make("cache/feature_store-v1",db_name="pucb.db")

2023-06-19 20:27:24 [info     ] APIs of mlopskit               model_name=feature_store model_version=1 ops_type=cache
2023-06-19 20:27:24 [info     ] The list of all versions for the current model is [1, 2].
2023-06-19 20:27:24 [warning  ] The version 1 is out of date. You should consider upgrading to version `v2`.
2023-06-19 20:27:24 [info     ] Usage of mlopskit-cache        Params={'db_type': 'rlite/redis/sfdb/diskcache, default:rlite', 'return_type': 'dblink/dbobj, default: dbobj', 'db_name': 'default: rlite_model.cache'}


In [3]:
test=PUCB(action_n=3,model_db=model_db)

In [87]:
import numpy as np

p=[1/3,1/3,1.0/3]
for i in range(10):
    c=test.act(priors=np.array(p),model_id='test')
    print(c)

1
2
2
1
2
2
1
2
2
2


In [34]:
test.learn(2,1.0,"test")

In [66]:
test.get_weights("test")

(array([7., 0., 4.]),
 array([0.09859155, 0.        , 0.04301075]),
 array([131.,  71., 119.]))

In [84]:
test.learn(0,3.0,"test")

In [85]:
test.get_weights("test")

(array([10.,  0.,  4.]),
 array([0.04739336, 0.        , 0.04301075]),
 array([211.,  71., 119.]))

In [89]:
price_dict = {
    "DC1": 0.99,
    "DC2": 1.99,
    "DC3": 2.99,
    "DC4": 3.99,
    "DC5": 4.99,
    "DC6": 5.99,
    "DC7": 7.99,
    "DC8": 9.99,
    "DC9": 11.99,
    "DC10": 14.99,
    "DC11": 19.99,
    "DC12": 24.99,
    "DC13": 29.99,
    "DC14": 39.99,
    "DC15": 49.99,
    "DC16": 59.99,
    "DC17": 69.99,
    "DC18": 79.99,
    "DC19": 89.99,
    "DC20": 99.99,
    "DC21": 109.99,
    "DC22": 119.99,
    "DC23": 124.99,
    "DC24": 139.99,
    "DC25": 149.99,
    "DC26": 159.99,
    "DC27": 169.99,
    "DC28": 179.99,
    "DC29": 189.99,
    "DC30": 199.99,
    "DC31": 249.99,
    "DC32": 299.99,
    "DC33": 349.99,
    "DC34": 399.99,
}



index_dict = {key: index for index, key in enumerate(price_dict.keys())}

index_dict

{'DC1': 0,
 'DC2': 1,
 'DC3': 2,
 'DC4': 3,
 'DC5': 4,
 'DC6': 5,
 'DC7': 6,
 'DC8': 7,
 'DC9': 8,
 'DC10': 9,
 'DC11': 10,
 'DC12': 11,
 'DC13': 12,
 'DC14': 13,
 'DC15': 14,
 'DC16': 15,
 'DC17': 16,
 'DC18': 17,
 'DC19': 18,
 'DC20': 19,
 'DC21': 20,
 'DC22': 21,
 'DC23': 22,
 'DC24': 23,
 'DC25': 24,
 'DC26': 25,
 'DC27': 26,
 'DC28': 27,
 'DC29': 28,
 'DC30': 29,
 'DC31': 30,
 'DC32': 31,
 'DC33': 32,
 'DC34': 33}

In [96]:
def get_index_list(price_dict, index_dict, min_price, max_price):
    index_list = []
    for dc, price in price_dict.items():
        if min_price <= price <= max_price:
            index_list.append(index_dict[dc])
    return index_list


get_index_list(price_dict,index_dict,0,0.1)

[]

In [100]:
def get_price_by_index(price_dict, index_dict, index):
    dc = list(index_dict.keys())[list(index_dict.values()).index(index)]
    price = price_dict[dc]
    return price


get_price_by_index(price_dict, index_dict, 1)



1.99

In [ ]:
from minirl.brain.cmab import LinUCB

test=LinUCB(actions=[1,2,3],obs_dim=4,model_db=model_db)