In [1]:
from minirl.algos.a2c import A2C

In [2]:
import gym
env = gym.make("CartPole-v1")
ob_n = env.observation_space.shape[0]
ac_n = env.action_space.n


test = A2C(ob_n,ac_n)

Softmax must use cross entropy loss
Softmax must use cross entropy loss
Could not load weights: File Not Found, use default
Could not load weights: File Not Found, use default


In [4]:
ac_n

2

In [3]:
import numpy as np
state = np.expand_dims(obs, axis=1)
state



NameError: name 'obs' is not defined

In [16]:
%%time
import numpy as np
obs, _ = env.reset()
state = np.expand_dims(obs, axis=1)
action,p = test.act(state)

CPU times: user 806 µs, sys: 1.01 ms, total: 1.81 ms
Wall time: 1.71 ms


In [19]:
obs_list=[]

In [21]:
obs, _ = env.reset()
obs_list.append(obs)

In [22]:
obs_list

[array([-0.00208154,  0.03989721,  0.04567558,  0.04808117], dtype=float32),
 array([-0.03967952,  0.0283169 , -0.00230562, -0.01212178], dtype=float32)]

In [23]:
np.reshape(obs_list, [1, -1])

array([[-0.00208154,  0.03989721,  0.04567558,  0.04808117, -0.03967952,
         0.0283169 , -0.00230562, -0.01212178]], dtype=float32)

In [15]:
mb_states

[array([[-0.04730239],
        [-0.04990605],
        [-0.03703809],
        [-0.00909954]], dtype=float32),
 array([[-0.04730239],
        [-0.04990605],
        [-0.03703809],
        [-0.00909954]], dtype=float32)]

In [4]:
next_state, reward, done,_, _ = env.step(action)

In [14]:
c

array([-0.04279293,  0.15251337,  0.04241492, -0.24093306], dtype=float32)

In [5]:
mb_states = []
mb_next_states = []
mb_actions = []
mb_action_probs = []
mb_clipped_rewards = []
mb_dones = []
mb_states.append(state)
_next_state=np.expand_dims(next_state, axis=1)
mb_next_states.append(_next_state)
mb_actions.append(action)
mb_dones.append(done)
mb_clipped_rewards.append(reward)
mb_action_probs.append(p)

In [8]:
mb_states.append(state)
_next_state=np.expand_dims(next_state, axis=1)
mb_next_states.append(_next_state)
mb_actions.append(action)
mb_dones.append(done)
mb_clipped_rewards.append(reward)
mb_action_probs.append(p)

In [9]:
mb_states

[array([[-0.04730239],
        [-0.04990605],
        [-0.03703809],
        [-0.00909954]], dtype=float32),
 array([[-0.04730239],
        [-0.04990605],
        [-0.03703809],
        [-0.00909954]], dtype=float32)]

In [15]:
dr=np.vstack(mb_clipped_rewards)
class rr:
    def discount_rewards(self, rewards, gamma):
        """take 1D float array of rewards and compute discounted reward"""
        r = rewards
        discounted_r = np.zeros_like(r)
        running_add = 0
        for t in reversed(range(0, r.size)):
            if r[t] != 0:
                running_add = (
                    0  # reset the sum, since this was a game boundary (pong specific!)
                )
            running_add = running_add * gamma + r[t]
            discounted_r[t] = running_add

        #discounted_r -= np.mean(discounted_r)
        #print(discounted_r)
        #discounted_r /= np.std(discounted_r)
        return discounted_r
    
rr().discount_rewards(dr,0.99)

array([[1.]])

In [12]:
np.hstack(mb_states)

array([[-0.04730239, -0.04730239],
       [-0.04990605, -0.04990605],
       [-0.03703809, -0.03703809],
       [-0.00909954, -0.00909954]], dtype=float32)

In [10]:
test.learn(states =mb_states , 
           actions=mb_actions, 
           action_probs=mb_action_probs,
           next_states=mb_next_states, 
           rewards=mb_clipped_rewards, 
           dones=mb_dones)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [5]:
import numpy as np
env_action_max = (-1, 1)[1]
np.expand_dims([env_action_max], axis=1)

array([[1]])