In [22]:
from minirl import PGAgent
test = PGAgent(6,2)

In [18]:
test.act([1,1,1,1,1.1,1])

0

In [23]:
test.add_step_reward(0)

In [24]:
test.rewards

[0]

In [7]:
from minirl.core.bandit import EpsilonGreedy
policy = EpsilonGreedy(epsilon=0, n_actions=35, seed=101)

In [19]:
%%time
action = policy.act()
action

CPU times: user 119 µs, sys: 8 µs, total: 127 µs
Wall time: 134 µs


0

In [6]:
policy._rewards

defaultdict(<bound method Base.clone of Mean: 0.>,
            {0: Mean: 0.,
             1: Mean: 0.,
             2: Mean: 0.,
             3: Mean: 0.,
             4: Mean: 0.,
             5: Mean: 0.,
             6: Mean: 0.,
             7: Mean: 0.,
             8: Mean: 0.,
             9: Mean: 0.,
             10: Mean: 0.,
             11: Mean: 0.,
             12: Mean: 0.,
             13: Mean: 0.,
             14: Mean: 0.,
             15: Mean: 0.,
             16: Mean: 0.,
             17: Mean: 0.,
             18: Mean: 0.,
             19: Mean: 0.,
             20: Mean: 0.,
             21: Mean: 0.,
             22: Mean: 0.,
             23: Mean: 0.,
             24: Mean: 0.,
             25: Mean: 0.,
             26: Mean: 0.,
             27: Mean: 0.,
             28: Mean: 0.,
             29: Mean: 0.,
             30: Mean: 0.,
             31: Mean: 0.,
             32: Mean: 0.,
             33: Mean: 0.,
             34: Mean: 0.})

In [4]:
policy.update(0,1.0)

Arm ID   Reward     Pulls   Share    
     0   Mean: 1.       1   100.00%  

In [23]:
test.best_score

0

In [61]:
test.score_history

deque([-1.0, 1.0, -1.0, 0, 0], maxlen=10)

In [23]:
test.learn()

IndexError: index 1 is out of bounds for axis 0 with size 1

In [43]:
import numpy as np
np.concatenate(test.policy.cache["fwd_x"])

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [33]:
#test.policy.params

In [117]:
for i in range(10):
    print(test.act([1,1,0]))

0
0
0
0
1
1
0
1
1
1


In [14]:
test.policy.cache

{'fwd_x': [array([[1. , 1. , 1. , 1. , 1.1, 1. ]]),
  array([[1. , 1. , 1. , 1. , 1.1, 1. ]]),
  array([[1. , 1. , 1. , 1. , 1.1, 1. ]])],
 'fwd_affine1': [array([[-0.24196331,  0.5643229 ,  0.42433789,  0.55205656, -0.79440887,
           0.34363373, -0.65352697,  0.01999138, -1.40406621,  0.14235929,
           0.73615992,  1.4586664 , -0.25169044,  0.1880506 ,  0.23271287,
          -0.81621706, -0.43932295, -0.6670344 ,  0.30556037, -1.06752331,
          -0.37506985, -0.31372841,  0.56091915, -0.81791911,  0.6242564 ,
          -0.44563584,  0.15469089, -1.15718655, -1.53902433,  0.92185658,
           0.59830651, -0.69085592, -1.16688766, -0.68858309, -0.65016297,
           0.26987426,  0.21999608, -0.00533719,  1.17652286,  0.19521371,
           0.64425469, -0.03173541,  0.59241906,  0.47788146,  0.51067986,
          -0.47704658, -0.68446067,  0.74291214, -0.35149811, -1.24513406,
           0.28525089,  0.23101348,  0.10120318, -0.27599275, -0.69042669,
           0.02323487