In [1]:
import numpy as np

A, b = [], []
D=3
for _ in range(5):
    A.append(np.eye(D))
    b.append(np.zeros(D))
            
            

In [3]:
A,b

([array([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
  array([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
  array([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
  array([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
  array([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]])],
 [array([0., 0., 0.]),
  array([0., 0., 0.]),
  array([0., 0., 0.]),
  array([0., 0., 0.]),
  array([0., 0., 0.])])

In [9]:
_A = A[0]
_b=b[0]
A_inv = np.linalg.inv(_A)
theta_hat = A_inv @ _b
theta_hat

array([0., 0., 0.])

In [7]:
_A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
feature_dim=3
H=1

tt=(-1 + 2 * np.random.rand(feature_dim, H)) / np.sqrt(feature_dim)
tt,tt.T

(array([[ 0.39691629],
        [ 0.50576413],
        [-0.45650851]]),
 array([[ 0.39691629,  0.50576413, -0.45650851]]))

In [12]:
theta = np.dot(np.linalg.inv(_A), _b)
theta.T

array([0., 0., 0.])